version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports: 
      - 8000:8000
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=social
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=notTheProductionKey
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRATION_MINUTES=30
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=social
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:

